name: cibuildwheel macOS13 repro

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build wheels on macOS 13
    runs-on: macOS-13

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel twine

      - name: Build wheels with cibuildwheel
        run: cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ENVIRONMENT_MACOS: |
            MACOSX_DEPLOYMENT_TARGET=13.0
          CIBW_BUILD: cp311-*
          CIBW_SKIP: "*-win32 *-manylinux_i686 pp* *-musllinux*"
          CIBW_REPAIR_WHEEL_COMMAND: ""

      - name: Show wheel tags
        run: |
          ls wheelhouse
          unzip -p wheelhouse/*.whl '*.dist-info/WHEEL' | grep Tag

      - name: Check metadata
        run: twine check wheelhouse/*

      # OPTIONAL: publish to TestPyPI (requires TEST_PYPI_API_TOKEN secret)
      - name: Publish to TestPyPI
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
